#!/usr/bin/env bash

PRODUCT="$1"

ANDROID_RELEASE=$(cat "src/rom/out/target/product/${PRODUCT}/ANDROID_RELEASE")

mkdir -p "lib/images/android/${ANDROID_RELEASE}/${PRODUCT}"
mv "src/rom/out/target/product/${PRODUCT}/ANDROID_RELEASE"              "lib/images/android/${ANDROID_RELEASE}/${PRODUCT}/ANDROID_RELEASE"
mv "src/rom/out/target/product/${PRODUCT}/android_system_disk.metadata" "lib/images/android/${ANDROID_RELEASE}/${PRODUCT}/"
mv "src/rom/out/target/product/${PRODUCT}/android_system_disk.vdi"      "lib/images/android/${ANDROID_RELEASE}/${PRODUCT}/"
mv "src/rom/out/target/product/${PRODUCT}/android_data_disk.vdi"        "lib/images/android/${ANDROID_RELEASE}/${PRODUCT}/"
